#!/usr/bin/env bash
# Summarize commit history and diff of given Markdown files in Git
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2013-11-18
set -eu

Here=$(dirname "$0")
PATH="$Here:$PATH" # add this directory to PATH for markdown-wdiff

since=$1; shift

# summarize commit history
{
    echo "\$ git log --oneline "$since"..HEAD $*"
    git log --oneline "$since"..HEAD "$@"
} |
sed 's/^/    /'
echo

# and embed the overall word diff
git diff ${GIT_DIFF_OPTS:-} --word-diff --patch-with-stat \
    --minimal --patience \
    "$since" -- "$@" |
sed '
    # format prologue
    1,/^diff /{
        /^diff/! s/^/    /
    }

    # format file headers
    /^diff /,/^+++ /{
        /^diff /{
            s|^diff .* \([^/]/\)\(.*\)|<div class="file-start"><code>\2</code></div>|
            a\
    \

        }
        /^<div class="file-start">/! s/^/    /
    }

    # format hunks
    /^@@ -.* +.* @@/{
        s| @@.*| @@|
        s|^|<div class="hunk-start"><code>|
        s|$|</code></div>|
    }
' |
markdown-format-wdiff
